### PR TITLE
add HeatmapGraph

### LINKED ISSUE #55: heatmap
## Description
Simple heatmap visualization. Start for matrix of pvalue

The visualization needs to provide option to easily set a threshold for colors

### PR DESCRIPTION
**Pull request by khillion**
## Description

Add support for heatmap and use it for visualization of diversity p-values.

#### Changelogs

* add `HeatmapGraph` to support heatmap visualization (`plot.graphs.heatmap`)
* use heatmap visualization when analyzing groups in diversity. Can choose to visualize or not with `show_pval` option.

#### Issue(s)

Fixes #55 

## Definition of Done

* [ ]  New code is tested with unit tests
* [ ]  Documentation has been updated
* [x]  Pull Request has been revised by a maintainer of the project

### CODE REVIEW

**Comment by khillion** [comment]
converted to draft to handle output_file option for pvalue graph

**Review by AgnesBaud — APPROVED** [review]
Looks great!

**Comment by AgnesBaud** [comment]
Just one question related to the p-value correction I'm working on, what kind of input does Heatmap take? Only symmetric dataframe?

**Comment by khillion** [comment]
> Just one question related to the p-value correction I'm working on, what kind of input does Heatmap take? Only symmetric dataframe?

@AgnesBaud `HeatmapGraph` takes whatever dataframe you give it to represent it. You will have indexes as y and columns as x and the content of each cells as z. So for the context of p-value, you need to make sure it is a dataframe.

**Pull request merged**
